name: Update RSVP Data

on:
  push:
    branches:
      - main

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "alex.ferreira.ferro@gmail.com"
          git config --global user.name "Alex Ferreira"
          git remote remove origin || true
          git remote add origin https://github.com/alexfferro/festa-leo.git
          git push --set-upstream origin main
      - name: Update RSVP data
        run: |
          echo '[]' > .github/rsvp.json
          git add .github/rsvp.json
          git commit -m "Update RSVP data" || true
          git push
